---
# tasks file for php-fpm


  - name: install remi repo
    dnf:
      name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
      state: present
      disable_gpg_check: yes

  - name: enable remi
    command: dnf module enable php:remi-7.4 -y

  - name: install php
    dnf:
      name:
        - php
        - php-cli
        - php-common
        - php-fpm
        - php-gd
        - php-intl
        - php-mbstring
        - php-pdo
        - php-mysql
        - php-soap
        - php-opcache
        - php-json
        - php-xml
        - php-xmlrpc
  #      - php-imagick
  #      - ImageMagick
        - php-memcached
        - php-redis
  #      - redis
  #      - memcached
        - php-devel
        - php-pear
      
      state: present
    notify:
      - php-fpm systemd
